window.__NUXT__ = (function (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, _, $, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, aA) {
	return {
		layout: "default",
		data: [{
			id: "790442",
			seo: {
				title: "2019 Copenhagenize Index",
				description: "The most comprehensive and holistic ranking of the bicycle-friendly cities on planet earth",
				twitterCard: m,
				image: {
					url: "https:\u002F\u002Fwww.datocms-assets.com\u002F10542\u002F1562162203-logo-solo.png"
				}
			},
			hero: m,
			heroVideoUrl: "https:\u002F\u002Fplayer.vimeo.com\u002Fexternal\u002F344965165.hd.mp4?s=966e419f1fbda24c35a7731a80fa19458798cb9f&profile_id=174",
			heroHeadline: "The Most Bicycle-Friendly Cities of 2019",
			heroDescription: "The Copenhagenize Index is the most comprehensive and holistic ranking of bicycle-friendly cities on planet earth.",
			blueButtonText: "See the list",
			ghostButtonText: "About the index",
			ghostButtonUrl: Y,
			successStories: [{
				id: Z,
				title: _,
				image: {
					url: $
				},
				city: aa,
				slug: ab
			}, {
				id: ac,
				title: ad,
				image: {
					url: ae
				},
				city: af,
				slug: ag
			}, {
				id: ah,
				title: ai,
				image: {
					url: aj
				},
				city: ak,
				slug: al
			}]
		}],
		error: m,
		state: {
			routes: {},
			cities: {
				cities: [{
					id: "787320",
					slug: "copenhagen",
					name: d,
					totalScore: "90.2",
					trend: a,
					infrastructure: am,
					culture: n,
					politics: am,
					index19: o,
					index17: o,
					index15: o,
					index13: p,
					index11: p,
					label: a
				}, {
					id: "795314",
					slug: "amsterdam",
					name: e,
					totalScore: "89.3",
					trend: a,
					infrastructure: an,
					culture: n,
					politics: n,
					index19: p,
					index17: w,
					index15: p,
					index13: o,
					index11: o,
					label: a
				}, {
					id: "795307",
					slug: "utrecht",
					name: q,
					totalScore: "88.4",
					trend: a,
					infrastructure: an,
					culture: n,
					politics: n,
					index19: w,
					index17: p,
					index15: w,
					index13: w,
					index11: a,
					label: a
				}, {
					id: "795333",
					slug: "antwerp",
					name: r,
					totalScore: "73.2",
					trend: a,
					infrastructure: K,
					culture: K,
					politics: L,
					index19: x,
					index17: s,
					index15: M,
					index13: s,
					index11: a,
					label: a
				}, {
					id: "787101",
					slug: "stasbourg",
					name: y,
					totalScore: "70.5",
					trend: a,
					infrastructure: K,
					culture: c,
					politics: L,
					index19: ao,
					index17: x,
					index15: N,
					index13: a,
					index11: a,
					label: a
				}, {
					id: "795318",
					slug: "bordeaux",
					name: t,
					totalScore: "68.8",
					trend: a,
					infrastructure: z,
					culture: c,
					politics: ap,
					index19: O,
					index17: O,
					index15: s,
					index13: ao,
					index11: a,
					label: a
				}, {
					id: "795366",
					slug: "oslo",
					name: P,
					totalScore: "62.5",
					trend: a,
					infrastructure: f,
					culture: b,
					politics: L,
					index19: s,
					index17: A,
					index15: a,
					index13: a,
					index11: a,
					label: "rising star"
				}, {
					id: "795348",
					slug: "paris",
					name: g,
					totalScore: "61.6",
					trend: a,
					infrastructure: f,
					culture: aq,
					politics: ap,
					index19: N,
					index17: Q,
					index15: A,
					index13: A,
					index11: O,
					label: a
				}, {
					id: "754790",
					slug: "vienna",
					name: B,
					totalScore: "60.7",
					trend: a,
					infrastructure: c,
					culture: b,
					politics: c,
					index19: M,
					index17: C,
					index15: h,
					index13: h,
					index11: u,
					label: a
				}, {
					id: "795363",
					slug: "helsinki",
					name: D,
					totalScore: "59.8",
					trend: a,
					infrastructure: f,
					culture: f,
					politics: E,
					index19: F,
					index17: u,
					index15: a,
					index13: a,
					index11: R,
					label: a
				}, {
					id: "795317",
					slug: "bremen",
					name: ar,
					totalScore: "58.9",
					trend: a,
					infrastructure: as,
					culture: c,
					politics: b,
					index19: at,
					index17: a,
					index15: a,
					index13: a,
					index11: a,
					label: G
				}, {
					id: "795356",
					slug: "bogota",
					name: au,
					totalScore: "58.1",
					trend: a,
					infrastructure: b,
					culture: H,
					politics: c,
					index19: C,
					index17: a,
					index15: a,
					index13: a,
					index11: a,
					label: G
				}, {
					id: "787311",
					slug: "barcelona",
					name: i,
					totalScore: "57.4",
					trend: a,
					infrastructure: b,
					culture: H,
					politics: z,
					index19: Q,
					index17: at,
					index15: C,
					index13: S,
					index11: "3",
					label: a
				}, {
					id: "795342",
					slug: "ljubljana",
					name: I,
					totalScore: "57.1",
					trend: a,
					infrastructure: f,
					culture: b,
					politics: z,
					index19: R,
					index17: N,
					index15: Q,
					index13: a,
					index11: a,
					label: a
				}, {
					id: "795345",
					slug: "berlin",
					name: j,
					totalScore: "56.3",
					trend: a,
					infrastructure: H,
					culture: E,
					politics: c,
					index19: "15",
					index17: F,
					index15: u,
					index13: F,
					index11: x,
					label: a
				}, {
					id: "795338",
					slug: "tokyo",
					name: v,
					totalScore: "55.4",
					trend: a,
					infrastructure: z,
					culture: f,
					politics: "1.9",
					index19: "16",
					index17: M,
					index15: a,
					index13: C,
					index11: x,
					label: a
				}, {
					id: "795359",
					slug: "taipei",
					name: av,
					totalScore: "54.5",
					trend: a,
					infrastructure: as,
					culture: E,
					politics: c,
					index19: S,
					index17: a,
					index15: a,
					index13: a,
					index11: a,
					label: G
				}, {
					id: "795360",
					slug: "vancouver",
					name: aw,
					totalScore: ax,
					trend: a,
					infrastructure: b,
					culture: H,
					politics: "2.6",
					index19: u,
					index17: a,
					index15: a,
					index13: a,
					index11: a,
					label: G
				}, {
					id: "754856",
					slug: "montreal",
					name: k,
					totalScore: ax,
					trend: a,
					infrastructure: b,
					culture: aq,
					politics: "3.0",
					index19: u,
					index17: h,
					index15: h,
					index13: R,
					index11: s,
					label: a
				}, {
					id: "795362",
					slug: "hamburg",
					name: l,
					totalScore: "52.7",
					trend: a,
					infrastructure: b,
					culture: "2.4",
					politics: E,
					index19: h,
					index17: S,
					index15: A,
					index13: h,
					index11: F,
					label: a
				}],
				rankHistory: [{
					year: "2011",
					cities: [{
						name: e
					}, {
						name: d
					}, {
						name: i
					}, {
						name: j
					}, {
						name: v
					}, {
						name: J
					}, {
						name: g
					}, {
						name: k
					}, {
						name: T
					}, {
						name: U
					}, {
						name: l
					}, {
						name: "Guadalajara"
					}, {
						name: "Portland"
					}, {
						name: "Stockholm"
					}, {
						name: D
					}, {
						name: "London"
					}, {
						name: "San Francisco"
					}, {
						name: ay
					}, {
						name: B
					}, {
						name: "New York"
					}]
				}, {
					year: "2013",
					cities: [{
						name: e
					}, {
						name: d
					}, {
						name: q
					}, {
						name: V
					}, {
						name: t
					}, {
						name: W
					}, {
						name: r
					}, {
						name: az
					}, {
						name: X
					}, {
						name: j
					}, {
						name: T
					}, {
						name: v
					}, {
						name: J
					}, {
						name: k
					}, {
						name: "Nagoya"
					}, {
						name: ay
					}, {
						name: i
					}, {
						name: U
					}, {
						name: g
					}, {
						name: l
					}]
				}, {
					year: "2015",
					cities: [{
						name: d
					}, {
						name: e
					}, {
						name: q
					}, {
						name: az
					}, {
						name: X
					}, {
						name: W
					}, {
						name: t
					}, {
						name: y
					}, {
						name: r
					}, {
						name: V
					}, {
						name: i
					}, {
						name: I
					}, {
						name: T
					}, {
						name: "Buenos Aires"
					}, {
						name: j
					}, {
						name: "Minneapolis"
					}, {
						name: g
					}, {
						name: l
					}, {
						name: J
					}, {
						name: k
					}]
				}, {
					year: "2017",
					cities: [{
						name: d
					}, {
						name: q
					}, {
						name: e
					}, {
						name: y
					}, {
						name: X
					}, {
						name: t
					}, {
						name: r
					}, {
						name: I
					}, {
						name: v
					}, {
						name: j
					}, {
						name: i
					}, {
						name: B
					}, {
						name: g
					}, {
						name: V
					}, {
						name: J
					}, {
						name: W
					}, {
						name: l
					}, {
						name: D
					}, {
						name: P
					}, {
						name: k
					}]
				}, {
					year: "2019",
					cities: [{
						name: d
					}, {
						name: e
					}, {
						name: q
					}, {
						name: r
					}, {
						name: y
					}, {
						name: t
					}, {
						name: P
					}, {
						name: g
					}, {
						name: B
					}, {
						name: D
					}, {
						name: ar
					}, {
						name: au
					}, {
						name: i
					}, {
						name: I
					}, {
						name: j
					}, {
						name: v
					}, {
						name: av
					}, {
						name: k
					}, {
						name: aw
					}, {
						name: l
					}]
				}]
			},
			cta: {
				cta: {
					headline: "Want our help?",
					description: "Get in touch for more information on the Copenhagenize Index",
					subjects: [{
						title: "Get an expert assessment of your city",
						downloadFile: m
					}, {
						title: "Talk to one of our bicycle urbanism experts",
						downloadFile: m
					}, {
						title: "Get Copenhagenize: The Definitive Guide to Global Bicycle Urbanism [excerpt]",
						downloadFile: {
							url: "https:\u002F\u002Fwww.datocms-assets.com\u002F10542\u002F1560179364-2018bookmattercopenhagenize.pdf"
						}
					}],
					formSubmissionRecipient: "index@copenhagenize.eu"
				}
			},
			nav: {
				menus: {
					main: [{
						id: "790321",
						title: "The Index",
						url: "\u002Fthe-index"
					}, {
						id: "790322",
						title: aA,
						url: Y
					}, {
						id: "790323",
						title: "Success Stories",
						url: "\u002Fsuccess-stories"
					}, {
						id: "894449",
						title: "Compare Cities",
						url: "\u002Fcompare"
					}],
					side: {
						title: aA,
						links: [{
							id: "794121",
							title: "About the Index",
							slug: "the-index"
						}, {
							id: "794127",
							title: "Methodology",
							slug: "methodology"
						}, {
							id: "794147",
							title: "FAQ",
							slug: "faq"
						}, {
							id: "794152",
							title: "Press",
							slug: "press"
						}]
					},
					footer: {
						description: "We are an urban design consultancy based in Copenhagen, Brussels and Montréal. We advise cities and governments in how to work towards a more bicycle-friendly urban landscape. Our solutions employ a wide spectrum of planning, urban design, communications and observational research, as opposed to solely focusing on engineering our cities. We develop human-centred solutions for transport in the modern city.",
						twitterUrl: "https:\u002F\u002Ftwitter.com\u002Fcopenhagenizers",
						facebookUrl: "https:\u002F\u002Fwww.facebook.com\u002Fcopenhagenize",
						instagramUrl: "https:\u002F\u002Fwww.instagram.com\u002Fcopenhagenizers",
						linkedinUrl: "https:\u002F\u002Fwww.linkedin.com\u002Fcompany\u002Fcopenhagenize"
					}
				}
			},
			stories: {
				stories: [{
					id: Z,
					position: 1,
					title: _,
					image: {
						url: $
					},
					city: aa,
					slug: ab
				}, {
					id: ac,
					position: 2,
					title: ad,
					image: {
						url: ae
					},
					city: af,
					slug: ag
				}, {
					id: ah,
					position: 3,
					title: ai,
					image: {
						url: aj
					},
					city: ak,
					slug: al
				}, {
					id: "972223",
					position: 4,
					title: "New Zealand ‘bike minister’ leads by example",
					image: {
						url: "https:\u002F\u002Fwww.datocms-assets.com\u002F10542\u002F1560263515-website.png"
					},
					city: "Auckland",
					slug: "strong-political-will-standout-new-zealand-bike-minister"
				}, {
					id: "792990",
					position: 5,
					title: "Fighting for self-determined, equitable urban mobility",
					image: {
						url: "https:\u002F\u002Fwww.datocms-assets.com\u002F10542\u002F1560263338-website.png"
					},
					city: "Tunis",
					slug: "bicycle-advocates-tunis-equitable-urban-mobility"
				}, {
					id: "972217",
					position: 6,
					title: "Increasing visibility for bicycles through public advocacy",
					image: {
						url: "https:\u002F\u002Fwww.datocms-assets.com\u002F10542\u002F1560263619-website.png"
					},
					city: U,
					slug: "increasing-visibility-for-bicycles-through-public-advocacy"
				}, {
					id: "972220",
					position: 7,
					title: "A yellow vision for Brussels: Marketing a city for bicycles ",
					image: {
						url: "https:\u002F\u002Fwww.datocms-assets.com\u002F10542\u002F1560264745-website.jpg"
					},
					city: "Brussels",
					slug: "yellow-vision-for-brussels-marketing-city-for-bicycles"
				}, {
					id: "972228",
					position: 8,
					title: "In over 70 Indian cities, cars take Sundays off, too",
					image: {
						url: "https:\u002F\u002Fwww.datocms-assets.com\u002F10542\u002F1560264924-website.png"
					},
					city: "Ahmedabad",
					slug: "70-indian-cities-cars-take-sundays-off"
				}, {
					id: "972224",
					position: 9,
					title: "A tasteful Turkish initiative to promote women on bikes ",
					image: {
						url: "https:\u002F\u002Fwww.datocms-assets.com\u002F10542\u002F1560264900-website.png"
					},
					city: "Izmir",
					slug: "tasteful-turkish-initiative-to-promote-women-on-bikes"
				}]
			}
		},
		serverRendered: true
	}
}("", "2.3", "2.8", "Copenhagen", "Amsterdam", "2.7", "Paris", "20", "Barcelona", "Berlin", "Montréal", "Hamburg", null, "3.8", "01", "02", "Utrecht", "Antwerp", "07", "Bordeaux", "18", "Tokyo", "03", "04", "Strasbourg", "2.5", "19", "Vienna", "12", "Helsinki", "2.1", "10", "newcomer", "2.2", "Ljubljana", "Munich", "3.3", "2.9", "09", "08", "06", "Oslo", "13", "14", "17", "Dublin", "Budapest", "Seville", "Nantes", "Malmö", "\u002Fabout\u002Fthe-index", "790437", "A new precedent for dockless bike share integration", "index.html\u002F\u002Fwww.datocms-assets.com\u002F10542\u002F1560194448-website.png", "Seattle", "seattle-dockless-bike-share", "790438", "A community-driven, cargo bike solution to a garbage crisis ", "index.html\u002F\u002Fwww.datocms-assets.com\u002F10542\u002F1560194615-website.png", "Lagos", "community-cargo-bike-solution-lagos-garbage-crisis", "790441", "Filling in the map to fill in the gaps ", "index.html\u002F\u002Fwww.datocms-assets.com\u002F10542\u002F1560265013-website.png", "Kuala Lumpur", "kuala-lumpur-bicycle-map", "4.0", "3.7", "05", "3.4", "1.8", "Bremen", "2.0", "11", "Bogotá", "Taipei", "Vancouver", "53.6", "Rio de Janeiro", "Eindhoven", "About"));
